export const GET_PROJECTS = 'GET_PROJECTS'
export const REGISTER_PROJECT = 'REGISTER_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const EXCLUDE_PROJECT = 'EXCLUDE_PROJECT'

export const GET_TASKS = 'GET_TASKS'
export const REGISTER_TASK = 'REGISTER_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
